// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzolUWTCTyfg_ZFZUa9InSIBbM-MIiN8A',
    appId: '1:675835178966:web:7ae9d732083d0689b9be77',
    messagingSenderId: '675835178966',
    projectId: 'smartcare-app-wearable-device',
    authDomain: 'smartcare-app-wearable-device.firebaseapp.com',
    storageBucket: 'smartcare-app-wearable-device.firebasestorage.app',
    measurementId: 'G-HLE9MZKX63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEUlgYVWzwSuzI2foW9keadAwFPDUnGQs',
    appId: '1:675835178966:android:1d0cd759a221f74cb9be77',
    messagingSenderId: '675835178966',
    projectId: 'smartcare-app-wearable-device',
    storageBucket: 'smartcare-app-wearable-device.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_u99VkmzXY8UJX5Ol4hE1Bcxr-sg09qM',
    appId: '1:675835178966:ios:26604bccb3c8d90ab9be77',
    messagingSenderId: '675835178966',
    projectId: 'smartcare-app-wearable-device',
    storageBucket: 'smartcare-app-wearable-device.firebasestorage.app',
    iosBundleId: 'com.example.smartcare',
  );

}