import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/app_state.dart';

class L10n {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'SmartCare',
      'iAmAPatient': 'I am a Patient',
      'iAmADoctor': 'I am a Doctor',
      'iAmAParent': 'I am a Parent',
      'doctorSignUp': 'Doctor Sign Up',
      'fullName': 'Full name',
      'createDoctorAccount': 'Create Doctor Account',
      'dr': 'Dr.',
      'noPatients': 'No patients linked to you yet.',
      'age': 'Age',
      'last': 'Last',
      'patientSignUp': 'Patient Sign Up',
      'gender': 'Gender',
      'female': 'Female',
      'male': 'Male',
      'other': 'Other',
      'occupation': 'Occupation',
      'location': 'Location',
      'maritalStatus': 'Marital status',
      'single': 'Single',
      'married': 'Married',
      'divorced': 'Divorced',
      'widowed': 'Widowed',
      'numChildren': 'Number of children',
      'emailOptional': 'Email (optional)',
      'doctorID': 'Doctor ID',
      'createPatient': 'Create Patient Account',
      'specialCondition': 'Special Condition (e.g., Autism)',
      'parentIDRequired': 'Parent ID (Required for under 18)',
      'welcome': 'Welcome',
      'settings': 'Settings',
      'sos': 'SOS',
      'heartRate': 'Heart Rate',
      'spo2': 'SpO₂',
      'temp': 'Temp',
      'glucose': 'Glucose',
      'alertsHistory': 'Alerts History',
      'mentalHealth': 'Mental Health',
      'aiBot': 'AI Bot',
      'medReminders': 'Medication Reminders',
      'trends': 'Trends',
      'waitingForVitals': 'Waiting for more vitals to show charts...',
      'useFakeData': 'Use Fake Sensor Data',
      'fakeInterval': 'Fake interval (sec)',
      'emergencyNum': 'Emergency Number',
      'sosMsg': 'SOS Message',
      'saveSettings': 'Save Settings',
      'toggleLang': 'تغيير إلى العربية',
      'settingsSaved': 'Settings saved',
    },
    'ar': {
      'appTitle': 'سمارت كير',
      'iAmAPatient': 'أنا مريض',
      'iAmADoctor': 'أنا طبيب',
      'iAmAParent': 'أنا ولي أمر',
      'doctorSignUp': 'تسجيل طبيب',
      'fullName': 'الاسم الكامل',
      'createDoctorAccount': 'إنشاء حساب طبيب',
      'dr': 'د.',
      'noPatients': 'لا يوجد مرضى مرتبطين بك حتى الآن.',
      'age': 'العمر',
      'last': 'آخر قراءة',
      'patientSignUp': 'تسجيل مريض',
      'gender': 'الجنس',
      'female': 'أنثى',
      'male': 'ذكر',
      'other': 'آخر',
      'occupation': 'الوظيفة',
      'location': 'الموقع',
      'maritalStatus': 'الحالة الاجتماعية',
      'single': 'أعزب',
      'married': 'متزوج',
      'divorced': 'مطلق',
      'widowed': 'أرمل',
      'numChildren': 'عدد الأطفال',
      'emailOptional': 'البريد الإلكتروني (اختياري)',
      'doctorID': 'معرّف الطبيب',
      'createPatient': 'إنشاء حساب مريض',
      'specialCondition': 'حالة خاصة (مثال: توحد)',
      'parentIDRequired': 'معرّف ولي الأمر (مطلوب لمن هم أقل من 18)',
      'welcome': 'أهلاً بك',
      'settings': 'الإعدادات',
      'sos': 'نجدة',
      'heartRate': 'معدل النبض',
      'spo2': 'الأكسجين',
      'temp': 'الحرارة',
      'glucose': 'الجلوكوز',
      'alertsHistory': 'سجل التنبيهات',
      'mentalHealth': 'الصحة النفسية',
      'aiBot': 'المساعد الذكي',
      'medReminders': 'تذكير الأدوية',
      'trends': 'المؤشرات',
      'waitingForVitals': 'في انتظار المزيد من البيانات لعرض الرسوم البيانية...',
      'useFakeData': 'استخدام بيانات وهمية',
      'fakeInterval': 'الفاصل الزمني للبيانات (ثانية)',
      'emergencyNum': 'رقم الطوارئ',
      'sosMsg': 'رسالة الطوارئ',
      'saveSettings': 'حفظ الإعدادات',
      'toggleLang': 'Switch to English',
      'settingsSaved': 'تم حفظ الإعدادات',
    },
  };

  static String get(BuildContext context, String key, {required Null Function(String? value) onChanged}) {
    final locale = Provider.of<AppState>(context, listen: false).locale;
    return _localizedValues[locale.languageCode]![key] ?? key;
  }
}